on: 
  schedule:
    - cron: 0 7 * * *

jobs:
  sync-with-upstream:
    runs-on: ubuntu-latest
    name: Fork Sync With Upstream
    steps:
    - id: step-1
      uses: aormsby/Fork-Sync-With-Upstream-action@v2.1
      with:
        upstream_repository: statsbomb/open-data
        upstream_branch: master
        target_branch: master

