- name: Fork Sync With Upstream
  uses: aormsby/Fork-Sync-With-Upstream-action@v2.1
  with:
    # Token for accessing the remote repo with authentication
    github_token: # optional
    upstream_repository: statsbomb/open-data
    upstream_branch: master
    target_branch: master

